module.exports = {
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  DUPLICATE_CONNECTION: 'DUPLICATE_CONNECTION',
  MESSAGE_PARSE_ERROR: 'MESSAGE_PARSE_ERROR',
  INVALID_SECURITY_TOKEN: 'INVALID_SECURITY_TOKEN'
}