# General
serverName: UUID
colors: true
showLogo: true
logLevel: INFO

# Connectivity
webServerEnabled: true
tcpServerEnabled: true
port: 6020
host: 0.0.0.0
tcpPort: 6021
tcpHost: 0.0.0.0
urlPath: /engine.io

# SSL Configuration
sslKey: null
sslCert: null
sslCa: null

# Plugin Configuration
plugins:

  # logger:
  #   name: default
  #
  # message:
  #   path: redis
  #   options:
  #     host: localhost
  #     port: 5672
  #
  # cache:
  #   path: memcached
  #   options:
  #     serverLocation: 'localhost:11211'
  #
  # storage:
  #   path: rethink
  #   options:
  #     host: localhost
  #     port: 28015

# Storage options
storageExclusion: null

# Security
maxAuthAttempts: 3
logInvalidAuthData: true
maxMessageSize: 1048576

#Authentication
auth:
  type: open

  # # or file type
  # type: file
  # # path to the user file
  # path: ./users.json
  # # the name of a HMAC digest algorithm
  # hash: 'md5'
  # # the number of times the algorithm should be applied
  # iterations: 100
  # # the length of the resulting key
  # keyLength: 32
  #
  # # or http type
  # type: http
  # endpointUrl: https://someurl.com/validateLogin
  # permittedStatusCodes: [ 200 ]
  # requestTimeout: 2000

# Permissioning
permissionType: config
permissionConfigPath: ./permissions.json
maxPermissionRuleIterations: 3
permissionCacheEvacuationInterval: 60000

# Timeouts
rpcProviderQueryTimeout: 1000
rpcProviderCacheTime: 60000
rpcAckTimeout: 1000
rpcTimeout: 10000
cacheRetrievalTimeout: 1000
storageRetrievalTimeout: 2000
dependencyInitialisationTimeout: 2000