FROM node:8.3.0-alpine

ENV DEEPSTREAM_PATH /opt/deepstream
ENV DEEPSTREAM_CONF /opt/deepstream/conf
ENV DEEPSTREAM_PLUGINS /opt/deepstream/plugins

RUN mkdir -p /opt

WORKDIR /opt

ADD conf /opt/deepstream/conf
ADD lib /opt/deepstream/plugins
ADD deepstream /opt/deepstream

WORKDIR $DEEPSTREAM_PATH

# 6020: WebSocket
EXPOSE 6020

VOLUME ["/opt/deepstream/conf", "/opt/deepstream/plugins"]

CMD ["./deepstream", "start", "--config", "/opt/deepstream/conf/config.yml", "--lib-dir", "/opt/deepstream/plugins"]