# Username
userA:
  password: "abcdefgh"
userB:
  password: "123456789"
  clientData:
    favorite color: orange
    id: userB
  serverData:
    invalid: invalid

A:
  password: "abcdefgh"
B:
  password: "abcdefgh"
C:
  password: "abcdefgh"
D:
  password: "abcdefgh"
W:
  password: "abcdefgh"

1:
  password: "abcdefgh"
2:
  password: "abcdefgh"
3:
  password: "abcdefgh"
4:
  password: "abcdefgh"
