#!/bin/sh
### BEGIN INIT INFO
# Provides:          deepstream
# Required-Start:    $remote_fs $network $syslog
# Required-Stop:     $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start deepstream at boot time
# Description:       Enable deepstream
### END INIT INFO

dir="/usr/bin/"
name="deepstream"
cmd="deepstream"

pid_file="/var/run/$name.pid"
stdout_log="/var/deepstream/$name.log"
stderr_log="/var/deepstream/$name.err"
conf_file="/etc/deepstream/config.yml"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        if [ ! -f "$conf_file" ]; then
            echo "Please provide a config file"
            exit 1
        fi

        echo "Starting $name.."
        cd "$dir"
        $cmd >> "$stdout_log" 2>&1 &
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name..."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0