#!/bin/sh
### BEGIN INIT INFO
# Provides:          deepstream
# Required-Start:    $remote_fs $network $syslog
# Required-Stop:     $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start deepstream at boot time
# Description:       Enable deepstream
### END INIT INFO

dir="/usr/bin/"
name="deepstream"
cmd="deepstream"

DEEPSTREAM_PID_FILE="/var/run/deepstream/$name.pid"
pid_file="/var/run/deepstream/$name.pid"
lib_dir="/var/lib/deepstream"

cd $dir

case "$1" in
    start)
        ./$cmd start > /dev/null &
    ;;
    stop)
        ./$cmd stop
    ;;
    status)
        ./$cmd status
    ;;
    *)
    echo "Usage: $0 {start|stop|status}"
    exit 1
    ;;
esac

exit 0